version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=desafioIgnite
      - POSTGRES_PASSWORD=desafioIgnite
      - POSTGRES_DB=desafioIgnite